### ISSUE TITLE
frontend deploy?

### ISSUE THREAD

**Issue by ghost** [yosriady/serverless-stripe-frontend#1]
Hi @yosriady,

Thanks for the guide, this repo and for the Going serverless PDF which are all very clear.
I understand that the frontend can be deployed anywhere...

**But what are your thoughts on the optimal way of doing this, considering next.js being SSR ? What's the advised workflow?**

Are you simply deploying it to S3? Are you also deploying it with Serverless (like the link below)?

[Serverless-Next](https://github.com/geovanisouza92/serverless-next)

Cheers!

**Comment by yosriady** [comment]
Hi @astenmies,

The simplest way to deploy would be https://zeit.co/now.

I believe the optimal deployment would to use the upcoming [`next export`](https://zeit.co/blog/next3-preview) command to build your Next.js app as a standalone static website - which you can then deploy on S3 + CDN / Netlify / elsewhere.

**Comment by ghost** [comment]
Hi @yosriady,

Thanks a lot, I did not know about `next export`, that's exactly the kind of solution I was looking for. `Now` is not the direction I want to take for my next.js projects.

Cheers
