### ISSUE TITLE
Tried doing this tutorial over the weekend and couldnt get it working..

### ISSUE THREAD

**Issue by CoaxiumVentures-zz** [yosriady/serverless-stripe-frontend#2]
Hello,

Issue #1 

When I do sls deploy I get the following warning

"A valid file to satisfy the declaration 'file(secrets.json)' could not be found."

After I download the files from git and run yarn, I get that the lamda-tester function is out of date.
I tried updating this JSON file but could never get the yarn test function to work. I suspect it was becuase I was using nodejs 8.11.3

Any plans of updating?

**Comment by yosriady** [comment]
The secrets.json file is something you need to create for the backend, not the frontend. Have you created a secrets.json file?

**Comment by CoaxiumVentures-zz** [comment]
My mistake... I should have posted this in the backend code.

I am using the front end provided by stripe.com

<form action="AWS API Gateway URL" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_jQdxd1TfHCN1p901N0orOHJJ"
    data-amount="999"
    data-name="Coaxium Ventures"
    data-description="Widget"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto"
    data-zip-code="true">
  </script>
</form>

This can be found on my website http://coaxium.io.s3-website-us-east-1.amazonaws.com

For the backend, I downloaded nodejs 8.11.3,npm and yarn, then serverless and your backend files from:
https://github.com/yosriady/serverless-stripe-backend

I added my secret key to the secrets.json.example file

When i run yarn I get the following error

error lambda-tester@3.0.2: The engine "node" is incompatible with this module. Expected version ">=6.0.0 <7.0.0".

I updated the package.json file to reflect the lastest version of the package: 3.4.1

https://github.com/vandium-io/lambda-tester

I run yarn again and it works. I now have a node_modules directory in my serverless-stripe-backend folder

If i run yarn test it doesnt work because I think my node js is too new

I run sls deploy

I get the error

 Serverless Warning --------------------------------------

  A valid file to satisfy the declaration 'file(secrets.json)' could not be found.


 Serverless Warning --------------------------------------

  A valid file to satisfy the declaration 'file(secrets.json)' could not be found.

I add the API url to my front end

<form action="https://dm47w8s7c7.execute-api.us-east-1.amazonaws.com/dev/charges" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_jQdxd1TfHCN1p901N0orOHJJ"
    data-amount="999"
    data-name="Coaxium Ventures"
    data-description="Widget"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto"
    data-zip-code="true">
  </script>
</form>

I try to submit a test payment and I get 

{"message": "Internal server error"}


02:20:19
START RequestId: f1f888f0-8e1e-11e8-9430-356b330fbd2d Version: $LATEST

02:20:19
2018-07-23T02:20:19.906Z	f1f888f0-8e1e-11e8-9430-356b330fbd2d	createCharge

02:20:19
2018-07-23T02:20:19.906Z	f1f888f0-8e1e-11e8-9430-356b330fbd2d	{ resource: '/charges', path: '/charges', httpMethod: 'POST', headers: { Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.9', 'cache-control': 'max-age=0', 'CloudFront-Forwarded-Proto': '

02:20:19
2018-07-23T02:20:19.913Z	f1f888f0-8e1e-11e8-9430-356b330fbd2d	SyntaxError: Unexpected token s in JSON at position 0 at Object.parse (native) at module.exports.handler (/var/task/functions/createCharge.js:6:28)

02:20:19
END RequestId: f1f888f0-8e1e-11e8-9430-356b330fbd2d

02:20:19
REPORT RequestId: f1f888f0-8e1e-11e8-9430-356b330fbd2d	Duration: 47.58 ms	Billed Duration: 100 ms Memory Size: 1024 MB	Max Memory Used: 28 MB

02:20:19
RequestId: f1f888f0-8e1e-11e8-9430-356b330fbd2d Process exited before completing request

**Comment by CoaxiumVentures-zz** [comment]
The event body variable looks like this:

stripeToken=tok_1CqtzfFpSv8dyTry7MbMiAZI&stripeTokenType=card&stripeEmail=test%40gmail.com

**Comment by yosriady** [comment]
You have to remove the .example suffix from the secrets.json file

**Comment by yosriady** [comment]
@milescadkins Did that solve the issue?

**Comment by CoaxiumVentures-zz** [comment]
It did yes.

It looks like I have issues with the front end I was using but think I have an idea of what needs to be done.

**Comment by CoaxiumVentures-zz** [comment]
Have you thought about making this code easy to deploy to s3??

https://www.fullstackreact.com/articles/deploying-a-react-app-to-s3/
 npm run build didnt work to create the index.html file
